---
title: "Replication of Study 1 by Levine et al. (2020, PNAS)"
author: "Sydney Levine (smlevine@mit.edu), Max Kleiman-Weiner, Laura Schulz, Joshua Tenenbaum, & Fiery Cushman"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---


## Introduction

Levine et al. showed in their paper "The logic of universalization guides moral judgement" that people (both adults and children) sometimes make moral judgements by considering the hypothetical situation "what if everyone did that?" -- a process that they call *universalization*. They contrast a computational model of universalization with other models of moral judgement in a variety of experiments that capture a kind of collective action "threshold problem". In this report, I aim to replicate Study 2a in which they contrast universalizaion with rule-based, outcome-based, and pessimistic outcome models of moral judgement.

I think this study is very relevant to my interests in social responsibility and the use of counterfactuals in understanding and evaluating each other's actions. The original (preregistered) study was conducted via MTurk and all the stimuli are given in [supplemental materials](https://github.com/psych251/levine2020/blob/master/original_paper/levine2020_universalization_supplement.pdf), so I will be aiming to replicate it exactly. I will be trying to recreate the left half of Figure 4 from the paper (and possibly also Figure S5 from the supplemental), and running the same statistical analyses. The main challenge will be coding the analysis since I've almost never analyzed data in R.

Links to [this repo](https://github.com/psych251/levine2020) and [the original paper](https://github.com/psych251/levine2020/blob/master/original_paper/levine2020_universalization.pdf).

## Methods

### Power Analysis

<!-- Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size. -->

### Planned Sample

Like the original study, participants will be recruited from MTurk. A smaller sample will be recruited due to financial constraints, but it will still be enough to report a result (if significant) based on a power analysis (TBD).

### Materials and Procedure

Participants will be assigned to either the High Interest or the Low Interest condition and read a story about fishing as follows:

> Twenty vacationers currently fish in a sustainable way, but then a new fishing hook becomes available that allows each vacationer to catch many more fish. If fewer than three vacationers start using the hook, there will be no negative consequences; if more than seven vacationers start using the hook, then there is guaranteed to be a total collapse of the fish population by summer’s end. Thus, the harm threshold occurs at three to seven interested parties. The protagonist of this vignette, John, is interested in using the new hook. Participants are asked if doing so would be morally acceptable.

The exact text shown to participants is provided in the [supplemental materials](https://github.com/psych251/levine2020/blob/master/original_paper/levine2020_universalization_supplement.pdf) with the instructions on lines 97-100, comprehension questions (exclusion crteria) on lines 97-96, the story itself on lines 174-218, and experiment questions on lines 134-145. These will all be shown in the same order and same format as the original study. The only difference is that five different stories were used in the original study while only one is selected here due to financial constraints, but this one story will still be an exact replication and the same effects will be tested.

### Analysis Plan

Data will be filtered using the same exclusion crteria as the original study: participants must correctly answer some comprehension questions in order to be included. After filtering the data, I'll average participants' responses (morally acceptability ratings) within the High Interest and Low Interest conditions, and compare the moral acceptability judgements between the two conditions by recreating the left half of Figure 4 from the paper. I'll determine whether the difference is significant with the same statistical test as the original study:

>  Using a chi-squared analysis, we will see if subjects in the Low Interest condition are significantly more likely to say that the action is morally acceptable compared to subjects in the High Interest condition.

Lastly, like the original study, I'll investigate whether participants' beliefs about rules or knowledge might explain their moral judgements instead. These were measured in the control questions.

For the "rule" question:

> There were only two subjects [out of 606 total] who answered that there was a rule on the lake forbidding the use of the hook. Judgments about the presence of a rule, therefore, do not explain subjects’ moral permissibility judgments.

For the "knowledge" question:

> We analyzed the knowledge question by looking at what proportion of subjects in each condition judged that no one would find out about John using the new hook (as opposed to thinking that 1 or more people would find out about it). There is a small but significant difference across the conditions ... (χ2(1) = 5.41, p = .020, two-tailed, V_Cramer = .09, CI95%[.01, .17], n = 608) ... we conducted a logistic regression to see if answers to the knowledge question could fully explain our finding (as we indicated we would do in the preregistration document), and, in fact, they could not. Once knowledge is added into the model along with condition, there is still a highly significant effect of condition.

So for these two questions, first a chi-squared analysis will be used to determine whether there is a significant difference in participants' answers by condition. If there is none, like for the rule question in the original study, then I can conclude that factor cannot explain people's moral acceptability judgements. If there *is* a significant difference, like for the knowledge question, then logistic regression with and without that factor can be conducted and compared to determine whether condition is still the main predictor of moral acceptability. If the same results are found in this replication as in the original study, then I should be able to recreate Figure S5 from the supplemental.

### Differences from Original Study

The recruiting process, materials, and experimental procedure used in this replication report will be the same as those in the original study. The only difference is that it will effectively be a replication at a smaller scale: less participants will be recruited and only one of five stories will be used. However, given that (1) the authors of the original study still found a significant result within each story, (2) their full model found no effect of which story was used, and (3) their combined results were very significant (p<0.001), I don't anticipate that this difference will make a large impact based on the claims in the original paper.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=T}
###Data Preparation

####Load Relevant Libraries and Functions
# library(dplyr)
# library(ggstatsplot)   # extension of ggplot2 with stats features

####Import data

#### Data exclusion / filtering
# Q1: include if answer is 19 && condition is high, or if answer is 0 && condition is low
# Q2: include if answer is 19, 20, or 21
# Q3: include if answer is 0
# Q4: include if answer is C (multiple choice A, B, or C)

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

- Side-by-side comparison of Figure 4 from paper
- Results of chi-squared analysis
- Results of analysis on rule and knowledge questions, and side-by-side comparison of Figure S5 from supplemental if necessary

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
